### ISSUE TITLE
Couple of observations

### ISSUE THREAD

**Issue by KernelPhreak** [0x78654C/xShell#1]
I know you didn't ask for help lol, but I'm bored and saw your new project pop up. 

In the condition where you're checking the user input commands, the comparison values seem incorrect. You’re using strcmp(buffer, "pwd") == 10, but strcmp returns 0 when the strings are equal, not 10. This condition should be corrected for all commands as strcmp(buffer, "command") == 0.

```
if (strcmp(buffer, "pwd\n") == 0)
if (strcmp(buffer, "clear\n") == 0)
if (strcmp(buffer, "whoami\n") == 0)
if (strcmp(buffer, "ls\n") == 0)
```

The fgets function captures the newline character (\n) after pressing Enter. To avoid issues with comparison, you need to remove the newline character before performing the comparison.

`buffer[strcspn(buffer, "\n")] = 0;  // Remove newline`

The message "Unknown command..." is printed regardless of the input. It should be moved into an else block that handles unrecognized commands.

```
if (strcmp(buffer, "pwd") == 0) { ... }
else if (strcmp(buffer, "clear") == 0) { ... }
else if (strcmp(buffer, "whoami") == 0) { ... }
else if (strcmp(buffer, "ls") == 0) { ... }
else {
    printf("Unknown command...\n");
}
```

The ls function is currently hardcoded to open the directory "a". Instead, you should pass the current directory (".") or handle arguments properly.

```
if (strcmp(buffer, "ls") == 0)
{
    char *arg = ".";
    ls(arg);
}
```

Should look something like this

```

int main (int argc, char *argv[])
{
    while(1) {
        if(isatty(STDIN_FILENO)) {
            char hostname[1024];

            // Get user name
            pw = getpwuid(getuid());

            // Get hostname
            gethostname(hostname, sizeof(hostname));

            // Print PS1
            print_ps1(pw->pw_name, hostname);

            // Get commands
            char buffer[50];
            if(fgets(buffer, sizeof(buffer), stdin) != NULL) {
                buffer[strcspn(buffer, "\n")] = 0;  // Remove newline

                // pwd
                if(strcmp(buffer, "pwd") == 0) {
                    char cwd[1024];
                    getcwd(cwd, sizeof(cwd));
                    printf("%s\n", cwd);
                }
                // clear
                else if(strcmp(buffer, "clear") == 0) {
                    clearScreen();
                }
                // whoami
                else if(strcmp(buffer, "whoami") == 0) {
                    printf("%s\n", pw->pw_name);
                }
                // ls
                else if(strcmp(buffer, "ls") == 0) {
                    char *arg = ".";
                    ls(arg);
                }
                else {
                    printf("Unknown command...\n");
                }
            }
        }
    }
}
```

**Comment by 0x78654C** [comment]
Hey Tojo,
Thanks for pointing out. Hmm I will test. Yes, the else block in wrong position .
If (strcmp(buffer, "ls") == 0)
{
    char *arg = ".";
    ls(arg);
}
I put here with 'a' because i need to figure out how to pass paths as well, not only current directory.

**Comment by 0x78654C** [comment]
Fixed on the following commit
https://github.com/0x78654C/xShell/commit/2b8318d0e5db56f3be7431c31611590763897932
